### ISSUE TITLE
Problem med node hos Asle

### ISSUE THREAD

**Issue by dagognatt** [EmblaAS/Xi.issues#6]
Asles node er død, medbrakt til kontor for undersøkelse.

**Comment by dagognatt** [comment]
Rød power-led blinker, som tyder på noe power-relatert. 

Prøvde alternativ strømkilde, og ting fungerte som normalt.

**Comment by Yngve-XiGen** [comment]
Regner med det er transformatoren det var feil på, og ikke selve noden? Om så, er ikke dette et stort problem.

Ønsker du å ha noden hos deg en stund til? eller skal jeg montere opp igjen?

**Comment by dagognatt** [comment]
ja, usb-laderen det er feil på. Noden fungerer fint. 

Om du vil så kan du bytte ut laderen og montere den opp igjen.

**Comment by Yngve-XiGen** [comment]
Flott. Kommer å henter den etterhvert, men om du trenger den for videre testing av ett eller annet så kan du ha den en stund til. Knudtzon har tatt ferie denne uken.

**Comment by arneinge** [comment]
Jeg tror jeg leste at man trenger 1+ amp, litt abhengig av usb utstyr.

Benyttet 2amp apple usb ladere i min første rigg.

Arne

**Comment by dagognatt** [comment]
Da vet jeg ikke hvor denne har sitt opphav.
Oppgitt til 1A.. Har fungert fram til nå.

Den mandag 13. juli 2015 skrev arneinge notifications@github.com følgende:
